#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  LC_ALL: en_US.UTF-8

jobs:
  JDKxx_Matrix:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 21, 25 ]
        os: [ ubuntu-latest ]
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v6
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build all
      shell: bash
      run: ./mvnw -U -e -B -ntp clean install
    - name: Check for dirty workspace
      # When dependency is updated then the tck bndruns may have updated version ranges
      # If that happends we want to have it explicitly committed to the repository.
      shell: bash
      run: |
        DIRTY=$(git status --porcelain)
        if [ -n "$DIRTY" ]; then
          echo "::error title=Dirty workspace::Build modified files. Please run the build locally and commit all the changes."
          echo "$DIRTY" | while IFS= read -r line; do
            file="${line:3}"
            echo "::error file=$file,title=Unexpected change::This file was modified or created by the build"
          done
          exit 1
        fi
    - name: Upload pax-logging logs
      if: always()   # run even on build failure
      uses: actions/upload-artifact@v4
      with:
        name: pax-logs-jdk${{ matrix.java }}-${{ matrix.os }}-${{ github.run_id }}
        path: |
          **/target/**/*.log
          **/target/exam/**
          **/target/surefire-reports/**
        retention-days: 7
